- README.md
- packages/fr-config-pull/src/index.js
- packages/fr-config-pull/src/scripts/locales.js
- packages/fr-config-push/src/index.js
- packages/fr-config-push/src/scripts/index.js
- packages/fr-config-push/src/scripts/update-locales.js
Resolves: https://github.com/ForgeRock/fr-config-manager/issues/8
> Pull and push locale files

- packages/fr-config-push/src/scripts/udpate-managed-roles.js
- packages/fr-config-push/src/scripts/update-agents.js
- packages/fr-config-push/src/scripts/update-audit.js
- packages/fr-config-push/src/scripts/update-auth-trees.js
- packages/fr-config-push/src/scripts/update-connector-definitions.js
- packages/fr-config-push/src/scripts/update-connector-mappings.js
- packages/fr-config-push/src/scripts/update-cors.js
- packages/fr-config-push/src/scripts/update-email-provider.js
- packages/fr-config-push/src/scripts/update-email-templates.js
- packages/fr-config-push/src/scripts/update-idm-access-config.js
- packages/fr-config-push/src/scripts/update-idm-endpoints.js
- packages/fr-config-push/src/scripts/update-idm-schedules.js
- packages/fr-config-push/src/scripts/update-internal-roles.js
- packages/fr-config-push/src/scripts/update-kba-config.js
- packages/fr-config-push/src/scripts/update-locales.js
- packages/fr-config-push/src/scripts/update-managed-objects.js
- packages/fr-config-push/src/scripts/update-password-policy.js
- packages/fr-config-push/src/scripts/update-policies.js
- packages/fr-config-push/src/scripts/update-realm-config.js
- packages/fr-config-push/src/scripts/update-remote-servers.js
- packages/fr-config-push/src/scripts/update-scripts.js
- packages/fr-config-push/src/scripts/update-secret-mappings.js
- packages/fr-config-push/src/scripts/update-secrets.js
- packages/fr-config-push/src/scripts/update-service-objects.js
- packages/fr-config-push/src/scripts/update-services.js
- packages/fr-config-push/src/scripts/update-terms-and-conditions.js
- packages/fr-config-push/src/scripts/update-themes.js
- packages/fr-config-push/src/scripts/update-ui-config.js
- packages/fr-config-push/src/scripts/update-variables.js
fixes #12
Consistent messaging for push commands
> fixes #12 handling of nonexisting directories

- packages/fr-config-pull/src/helpers/cli-options.js
- packages/fr-config-pull/src/index.js
- packages/fr-config-pull/src/scripts/scripts.js
- packages/fr-config-push/src/helpers/cli-options.js
- packages/fr-config-push/src/index.js
- packages/fr-config-push/src/scripts/index.js
- packages/fr-config-push/src/scripts/update-auth-trees.js
- packages/fr-config-push/src/scripts/update-scripts.js
Resolves: https://github.com/ForgeRock/fr-config-manager/issues/21
> 21: Push individual journey

- packages/fr-config-push/src/scripts/update-secrets.js
Fix for issue: https://github.com/ForgeRock/fr-config-manager/issues/31
> 31 - push secrets error (#31)

- packages/fr-config-push/src/scripts/update-idm-endpoints.js
> 33 fr config push endpoints throws error

- packages/fr-config-push/src/index.js
Resolves: https://github.com/ForgeRock/fr-config-manager/issues/35
> Issue with authentication config in fr-config-push all-static

- packages/fr-config-pull/src/index.js
- packages/fr-config-push/src/index.js
Resolves: https://github.com/ForgeRock/fr-config-manager/issues/28
> 28: Order command line options

- packages/fr-config-pull/src/index.js
- packages/fr-config-push/src/index.js
Resolves: https://github.com/ForgeRock/fr-config-manager/issues/38
> 38: Don't authenticate on fr-config-push with no options

- README.md
- packages/fr-config-pull/README.md
- packages/fr-config-pull/src/index.js
- packages/fr-config-pull/src/scripts/configMetadata.js
- packages/fr-config-push/README.md
- packages/fr-config-push/src/helpers/cli-options.js
- packages/fr-config-push/src/index.js
- packages/fr-config-push/src/scripts/index.js
- packages/fr-config-push/src/scripts/update-config-metadata.js
Resolves: https://github.com/ForgeRock/fr-config-manager/issues/18
> 18: Configuration versioning

- packages/fr-config-push/src/scripts/update-idm-schedules.js
Resolves: https://github.com/ForgeRock/fr-config-manager/issues/43
> 43: Fix schedule push

- README.md
Resolves: https://github.com/ForgeRock/fr-config-manager/issues/48
> 48: Remove warning from README

- packages/fr-config-pull/package.json
- packages/fr-config-pull/src/index.js
- packages/fr-config-push/package.json
- packages/fr-config-push/src/index.js
Resolves: https://github.com/ForgeRock/fr-config-manager/issues/51
> 51: Version option

- packages/fr-config-common/src/constants.js
- packages/fr-config-pull/package.json
- packages/fr-config-pull/src/helpers/utils.js
- packages/fr-config-pull/src/scripts/amRealmConfig.js
- packages/fr-config-pull/src/scripts/amServices.js
- packages/fr-config-pull/src/scripts/authzPolicies.js
- packages/fr-config-pull/src/scripts/connectors.js
- packages/fr-config-pull/src/scripts/cors.js
- packages/fr-config-pull/src/scripts/emailTemplates.js
- packages/fr-config-pull/src/scripts/endpoints.js
- packages/fr-config-pull/src/scripts/fieldPolicy.js
- packages/fr-config-pull/src/scripts/idmFlatConfig.js
- packages/fr-config-pull/src/scripts/internalRoles.js
- packages/fr-config-pull/src/scripts/journeys.js
- packages/fr-config-pull/src/scripts/locales.js
- packages/fr-config-pull/src/scripts/managed.js
- packages/fr-config-pull/src/scripts/mappings.js
- packages/fr-config-pull/src/scripts/oauth2Agents.js
- packages/fr-config-pull/src/scripts/schedules.js
- packages/fr-config-pull/src/scripts/scripts.js
- packages/fr-config-pull/src/scripts/secretMappings.js
- packages/fr-config-pull/src/scripts/secrets.js
- packages/fr-config-pull/src/scripts/serviceObjects.js
- packages/fr-config-pull/src/scripts/termsAndConditions.js
- packages/fr-config-pull/src/scripts/themes.js
- packages/fr-config-pull/src/scripts/variables.js
Resolves: https://github.com/ForgeRock/fr-config-manager/issues/52
> 52: Safe filenames

- packages/fr-config-common/src/constants.js
- packages/fr-config-pull/src/scripts/themes.js
- packages/fr-config-push/src/scripts/update-themes.js
Resolves: https://github.com/ForgeRock/fr-config-manager/issues/55
> 55: Support for themes with locale settings

- package.json
- packages/fr-config-common/package.json
- packages/fr-config-pull/package.json
- packages/fr-config-push/package.json
Resolves: https://github.com/ForgeRock/fr-config-manager/issues/63
> 63: Version 1.1.1

- packages/fr-config-common/src/restClient.js
- packages/fr-config-push/src/scripts/update-secrets.js
Resolves: https://github.com/ForgeRock/fr-config-manager/issues/62
> 62: Secrets push failing for new secrets

- packages/fr-config-common/src/restClient.js
- packages/fr-config-common/src/utils.js
- packages/fr-config-pull/src/helpers/utils.js
- packages/fr-config-pull/src/scripts/amRealmConfig.js
- packages/fr-config-pull/src/scripts/amServices.js
- packages/fr-config-pull/src/scripts/authzPolicies.js
- packages/fr-config-pull/src/scripts/connectors.js
- packages/fr-config-pull/src/scripts/cors.js
- packages/fr-config-pull/src/scripts/emailTemplates.js
- packages/fr-config-pull/src/scripts/endpoints.js
- packages/fr-config-pull/src/scripts/fieldPolicy.js
- packages/fr-config-pull/src/scripts/idmFlatConfig.js
- packages/fr-config-pull/src/scripts/internalRoles.js
- packages/fr-config-pull/src/scripts/journeys.js
- packages/fr-config-pull/src/scripts/locales.js
- packages/fr-config-pull/src/scripts/managed.js
- packages/fr-config-pull/src/scripts/mappings.js
- packages/fr-config-pull/src/scripts/oauth2Agents.js
- packages/fr-config-pull/src/scripts/schedules.js
- packages/fr-config-pull/src/scripts/scripts.js
- packages/fr-config-pull/src/scripts/secretMappings.js
- packages/fr-config-pull/src/scripts/secrets.js
- packages/fr-config-pull/src/scripts/serviceObjects.js
- packages/fr-config-pull/src/scripts/termsAndConditions.js
- packages/fr-config-pull/src/scripts/themes.js
- packages/fr-config-pull/src/scripts/variables.js
- packages/fr-config-push/src/helpers/config-process.js
- packages/fr-config-push/src/scripts/update-agents.js
- packages/fr-config-push/src/scripts/update-service-objects.js
Resolves: https://github.com/ForgeRock/fr-config-manager/issues/67
> 67: Escape placeholder-like data in agent and service object config

- packages/fr-config-common/src/restClient.js
- packages/fr-config-pull/src/helpers/cli-options.js
- packages/fr-config-pull/src/index.js
- packages/fr-config-push/src/helpers/cli-options.js
- packages/fr-config-push/src/index.js
Resolves: https://github.com/ForgeRock/fr-config-manager/issues/71
> 71: Fix help for command options

- packages/fr-config-pull/src/scripts/scripts.js
- packages/fr-config-push/src/scripts/update-scripts.js
Resolves: https://github.com/ForgeRock/fr-config-manager/issues/74
> 74: Push script by name

- packages/fr-config-pull/src/scripts/managed.js
- packages/fr-config-push/src/scripts/update-managed-objects.js
Resolves: https://github.com/ForgeRock/fr-config-manager/issues/76
> 76: Break out action scripts in managed objects

- packages/fr-config-pull/src/helpers/cli-options.js
- packages/fr-config-pull/src/index.js
- packages/fr-config-pull/src/scripts/variables.js
- packages/fr-config-push/src/scripts/update-variables.js
Resolves: https://github.com/ForgeRock/fr-config-manager/issues/79
> 79: Dump option for variables

- packages/fr-config-common/src/restClient.js
- packages/fr-config-push/src/scripts/update-scripts.js
Resolves: https://github.com/ForgeRock/fr-config-manager/issues/81
> 81: New scripts throwing 404

- packages/fr-config-push/src/scripts/update-connector-mappings.js
Resolves: https://github.com/ForgeRock/fr-config-manager/issues/84
> 84: Mapping push by name wiping other mappings

- packages/fr-config-pull/src/scripts/scripts.js
Resolves: https://github.com/ForgeRock/fr-config-manager/issues/89
> 89: Check for duplicate scripts

- packages/fr-config-push/src/scripts/update-secret-mappings.js
Resolves: https://github.com/ForgeRock/fr-config-manager/issues/92
> 92: 403 on fr-config-push secret-mappings

- packages/fr-config-common/src/constants.js
- packages/fr-config-pull/src/scripts/themes.js
- packages/fr-config-push/src/scripts/update-themes.js
Resolves: https://github.com/ForgeRock/fr-config-manager/issues/100
> 10: Split out journeyFooterScriptTag in theme config

- .env.sample
- packages/fr-config-common/src/authenticate.js
- packages/fr-config-common/src/constants.js
- packages/fr-config-pull/README.md
- packages/fr-config-pull/src/index.js
- packages/fr-config-pull/src/scripts/csp.js
- packages/fr-config-push/README.md
- packages/fr-config-push/src/index.js
- packages/fr-config-push/src/scripts/index.js
- packages/fr-config-push/src/scripts/update-csp.js
Resolves: https://github.com/ForgeRock/fr-config-manager/issues/102
> 102: Support for CSP config

- README.md
Resolves: https://github.com/ForgeRock/fr-config-manager/issues/103
> 103: Fixes to README quickstart notes

- README.md
Resolves: https://github.com/ForgeRock/fr-config-manager/issues/107
> 107: README quickstart

- README.md
- docs/esvs.md
- packages/fr-config-pull/src/helpers/cli-options.js
- packages/fr-config-pull/src/index.js
- packages/fr-config-pull/src/scripts/secrets.js
- packages/fr-config-push/src/helpers/cli-options.js
- packages/fr-config-push/src/index.js
- packages/fr-config-push/src/scripts/update-secrets.js
- packages/fr-config-push/src/scripts/update-variables.js
Resolves: https://github.com/ForgeRock/fr-config-manager/issues/70
> 70: Only update ESVs if changed

- packages/fr-config-push/src/scripts/update-connector-mappings.js
Resolves: https://github.com/ForgeRock/fr-config-manager/issues/109
> 109: validSource and validTarget mapping scripts

- packages/fr-config-pull/src/index.js
- packages/fr-config-pull/src/scripts/idmFlatConfig.js
Resolves: https://github.com/ForgeRock/fr-config-manager/issues/114
> 114: pull remote-servers 404

- packages/fr-config-push/src/scripts/update-secrets.js
- packages/fr-config-push/src/scripts/update-variables.js
Resolves: https://github.com/ForgeRock/fr-config-manager/issues/116
> 116: error when pushing new variables

- packages/fr-config-push/README.md
- packages/fr-config-push/src/helpers/cli-options.js
- packages/fr-config-push/src/index.js
- packages/fr-config-push/src/scripts/restart-fidc.js
Resolves: https://github.com/ForgeRock/fr-config-manager/issues/118
> 118: option to check for changes before restart

- packages/fr-config-push/src/scripts/update-policies.js
Resolves: https://github.com/ForgeRock/fr-config-manager/issues/120
> 120: 404 for authz-policies push

- .env.sample
- README.md
- package.json
- packages/fr-config-promote/LICENSE
- packages/fr-config-promote/README.md
- packages/fr-config-promote/package.json
- packages/fr-config-promote/src/helpers/cli-options.js
- packages/fr-config-promote/src/index.js
- packages/fr-config-promote/src/scripts/check-promotion-reports.js
- packages/fr-config-promote/src/scripts/check-promotion-status.js
- packages/fr-config-promote/src/scripts/check-tenants-locked.js
- packages/fr-config-promote/src/scripts/index.js
- packages/fr-config-promote/src/scripts/lock-tenants.js
- packages/fr-config-promote/src/scripts/run-promotion-dryrun.js
- packages/fr-config-promote/src/scripts/run-promotion.js
- packages/fr-config-promote/src/scripts/unlock-tenants.js
This tool is a first attempt to manage promotions. This can be handy to integrate with CD/CI pipelines.
> First Bèta of the fr-config-promote tool

- packages/fr-config-push/src/scripts/update-secrets.js
Resolves: https://github.com/ForgeRock/fr-config-manager/issues/131
> 131: push named secret

- packages/fr-config-common/src/restClient.js
- packages/fr-config-push/src/scripts/update-raw.js
Resolves: https://github.com/ForgeRock/fr-config-manager/issues/139
> 139: Try PUT then POST with create action

- packages/fr-config-common/src/restClient.js
- packages/fr-config-push/src/scripts/update-raw.js
Resolves: https://github.com/ForgeRock/fr-config-manager/issues/145
> 145: Raw push issues

- docs/esvs.md
- packages/fr-config-push/README.md
- packages/fr-config-push/src/helpers/cli-options.js
- packages/fr-config-push/src/index.js
- packages/fr-config-push/src/scripts/update-secrets.js
- packages/fr-config-push/src/scripts/update-variables.js
Resolves: https://github.com/ForgeRock/fr-config-manager/issues/146
> 146: Don't remove current secret

- packages/fr-config-promote/README.md
Resolves: https://github.com/ForgeRock/fr-config-manager/issues/148
> 148: Quickstart readme for promotion

- packages/fr-config-common/package.json
- packages/fr-config-promote/package.json
- packages/fr-config-pull/package.json
- packages/fr-config-push/package.json
Resolves: https://github.com/ForgeRock/fr-config-manager/issues/158
> 158: Scope packages

- README.md
Resolves: https://github.com/ForgeRock/fr-config-manager/issues/162
> 162: Roll back npm install README

- .npmignore
- README.md
- package.json
- packages/fr-config-common/package.json
- packages/fr-config-promote/package.json
- packages/fr-config-pull/package.json
- packages/fr-config-push/package.json
Resolves: https://github.com/ForgeRock/fr-config-manager/issues/171
> 171: Tidy up packaging for npm

- package.json
- packages/fr-config-common/package.json
- packages/fr-config-promote/package.json
- packages/fr-config-pull/package.json
- packages/fr-config-push/package.json
- packages/fr-config-push/src/scripts/update-auth-trees.js
- packages/fr-config-push/src/scripts/update-idm-endpoints.js
Resolves: https://github.com/ForgeRock/fr-config-manager/issues/175
> 175: glob issue

- packages/fr-config-pull/src/scripts/journeys.js
Resolves: https://github.com/ForgeRock/fr-config-manager/issues/179
> 179: Pull script dependencies within page nodes

- package.json
- packages/fr-config-common/package.json
- packages/fr-config-common/src/constants.js
- packages/fr-config-common/src/restClient.js
- packages/fr-config-common/src/utils.js
- packages/fr-config-promote/package.json
- packages/fr-config-pull/package.json
- packages/fr-config-pull/src/helpers/cli-options.js
- packages/fr-config-pull/src/index.js
- packages/fr-config-push/package.json
- packages/fr-config-push/src/helpers/cli-options.js
- packages/fr-config-push/src/index.js
- packages/fr-config-push/src/scripts/update-raw.js
Resolves: https://github.com/ForgeRock/fr-config-manager/issues/157
> 157: raw stdin and stdout

- package.json
- packages/fr-config-common/package.json
- packages/fr-config-promote/package.json
- packages/fr-config-pull/package.json
- packages/fr-config-push/package.json
- packages/fr-config-push/src/scripts/update-raw.js
Resolves: https://github.com/ForgeRock/fr-config-manager/issues/186
> 186: raw push 401/403

- package.json
- packages/fr-config-common/package.json
- packages/fr-config-common/src/utils.js
- packages/fr-config-promote/package.json
- packages/fr-config-pull/package.json
- packages/fr-config-pull/src/scripts/journeys.js
- packages/fr-config-push/package.json
- packages/fr-config-push/src/scripts/update-auth-trees.js
Resolves: https://github.com/ForgeRock/fr-config-manager/issues/184
> 184: pull/push dependent scripts for all node types

- packages/fr-config-promote/src/scripts/check-promotion-status.js
- packages/fr-config-promote/src/scripts/check-tenants-locked.js
- packages/fr-config-promote/src/scripts/lock-tenants.js
- packages/fr-config-promote/src/scripts/run-promotion-dryrun.js
- packages/fr-config-promote/src/scripts/run-promotion.js
- packages/fr-config-promote/src/scripts/unlock-tenants.js
Also, JSON parsing simulated JSON strings… 🤦‍♂️
> Always log JSON in promotion

- package.json
- packages/fr-config-common/package.json
- packages/fr-config-promote/package.json
- packages/fr-config-pull/package.json
- packages/fr-config-push/package.json
- packages/fr-config-push/src/scripts/update-idm-schedules.js
Resolves: https://github.com/ForgeRock/fr-config-manager/issues/204
> 204: Issue with task scanner push

- packages/fr-config-push/src/scripts/update-services.js
Resolves: https://github.com/ForgeRock/fr-config-manager/issues/207
> 207: 404 error when pushing new services

- package.json
- packages/fr-config-common/package.json
- packages/fr-config-common/src/restClient.js
- packages/fr-config-promote/package.json
- packages/fr-config-pull/package.json
- packages/fr-config-pull/src/index.js
- packages/fr-config-push/package.json
Resolves: https://github.com/ForgeRock/fr-config-manager/issues/126
> 126: verbose mode

- package.json
- packages/fr-config-common/package.json
- packages/fr-config-promote/package.json
- packages/fr-config-pull/package.json
- packages/fr-config-pull/src/index.js
- packages/fr-config-push/package.json
Resolves: https://github.com/ForgeRock/fr-config-manager/issues/214
> 214: Config metadata prints info message on pull

- package.json
- packages/fr-config-common/package.json
- packages/fr-config-common/src/restClient.js
- packages/fr-config-promote/package.json
- packages/fr-config-pull/package.json
- packages/fr-config-push/package.json
Resolves: https://github.com/ForgeRock/fr-config-manager/issues/216
> 216: debug object data

- package.json
- packages/fr-config-common/package.json
- packages/fr-config-promote/package.json
- packages/fr-config-promote/src/index.js
- packages/fr-config-pull/package.json
- packages/fr-config-push/package.json
- packages/fr-config-push/src/index.js
Resolves: https://github.com/ForgeRock/fr-config-manager/issues/220
> 220: Add debug for push and promote

- package.json
- packages/fr-config-common/package.json
- packages/fr-config-promote/package.json
- packages/fr-config-pull/package.json
- packages/fr-config-pull/src/helpers/cli-options.js
- packages/fr-config-pull/src/index.js
- packages/fr-config-pull/src/scripts/journeys.js
- packages/fr-config-push/package.json
add option to cleanup journey nodes directory on pull to remove deleted or renamed nodes
> Clean option for journeys

- package.json
- packages/fr-config-common/package.json
- packages/fr-config-promote/package.json
- packages/fr-config-pull/package.json
- packages/fr-config-pull/src/scripts/variables.js
- packages/fr-config-push/package.json
Resolves: https://github.com/ForgeRock/fr-config-manager/issues/203
> 207: Handle international characters for variable dump on pull

- package.json
- packages/fr-config-common/package.json
- packages/fr-config-promote/package.json
- packages/fr-config-pull/package.json
- packages/fr-config-pull/src/scripts/themes.js
- packages/fr-config-push/package.json
- packages/fr-config-push/src/scripts/update-secrets.js
- packages/fr-config-push/src/scripts/update-themes.js
Resolves: https://github.com/ForgeRock/fr-config-manager/issues/231
> 231: Remove atob and btoa

- package.json
- packages/fr-config-common/package.json
- packages/fr-config-promote/package.json
- packages/fr-config-pull/package.json
- packages/fr-config-pull/src/scripts/amServices.js
- packages/fr-config-push/package.json
- packages/fr-config-push/src/scripts/update-services.js
Resolves: https://github.com/ForgeRock/fr-config-manager/issues/242
> 242: Pull/push all secondary config

- package.json
- packages/fr-config-common/package.json
- packages/fr-config-promote/README.md
- packages/fr-config-promote/package.json
- packages/fr-config-promote/src/helpers/cli-options.js
- packages/fr-config-promote/src/index.js
- packages/fr-config-promote/src/scripts/check-tenants-locked.js
- packages/fr-config-promote/src/scripts/run-promotion.js
- packages/fr-config-pull/package.json
- packages/fr-config-push/package.json
Resolves: https://github.com/ForgeRock/fr-config-manager/issues/261
> 261: Promotion options

- package.json
- packages/fr-config-common/package.json
- packages/fr-config-promote/package.json
- packages/fr-config-promote/src/helpers/cli-options.js
- packages/fr-config-promote/src/index.js
- packages/fr-config-promote/src/scripts/check-promotion-reports.js
- packages/fr-config-pull/package.json
- packages/fr-config-push/package.json
Resolves: https://github.com/ForgeRock/fr-config-manager/issues/262
> 262: Provisional promotion report

- package.json
- packages/fr-config-common/package.json
- packages/fr-config-promote/README.md
- packages/fr-config-promote/package.json
- packages/fr-config-promote/src/helpers/cli-options.js
- packages/fr-config-promote/src/index.js
- packages/fr-config-promote/src/scripts/check-promotion-reports.js
- packages/fr-config-promote/src/scripts/index.js
- packages/fr-config-promote/src/scripts/rollback-promotion.js
- packages/fr-config-pull/package.json
- packages/fr-config-push/package.json
Resolves: https://github.com/ForgeRock/fr-config-manager/issues/263
> 263: Rollback

- package.json
- packages/fr-config-common/package.json
- packages/fr-config-common/src/restClient.js
- packages/fr-config-delete/package.json
- packages/fr-config-delete/src/index.js
- packages/fr-config-delete/src/scripts/scripts.js
- packages/fr-config-delete/tests/scripts.test.js
- packages/fr-config-promote/package.json
- packages/fr-config-pull/package.json
- packages/fr-config-push/package.json
Resolves #233 fr-config-delete scripts
Fixes #284 clashing dry-run option
> 233 fr config delete scripts

- package.json
- packages/fr-config-common/package.json
- packages/fr-config-delete/package.json
- packages/fr-config-promote/package.json
- packages/fr-config-pull/package.json
- packages/fr-config-push/package.json
- packages/fr-config-push/src/scripts/update-connector-mappings.js
Resolves: https://github.com/ForgeRock/fr-config-manager/issues/293
> 293: Expand result trigger in mappings
